version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
volumes:
  rabbitmq_data:
    driver: local
